name: Request Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [request-update-run-action]
  schedule:
    - cron: '0 19 * * *'
concurrency: 
  group: repo-update
  cancel-in-progress: false
jobs:
  generate-main:
    name: Generate main repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Run main generator
        env:
          GITHUB_TOKEN: ${{ secrets.MEOWRSTRIGGER }}
        run: |
          cd generators/main
          node index.js
      - name: Run global generator
        env:
          GITHUB_TOKEN: ${{ secrets.MEOWRSTRIGGER }}
        run: |
          cd generators/global
          node index.js
      - name: Run pants generator
        env:
          GITHUB_TOKEN: ${{ secrets.MEOWRSTRIGGER }}
        run: |
          cd generators/pants
          node index.js
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin main
          git checkout main
          git add meowrs.json
          git add repo.json
          git add global.json
          git add pants.json
          git diff --cached --quiet && exit 0
          git commit -m "Update main repository"
          git push

  generate-global:
    name: Generate global repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: global
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Run generator
        env:
          GITHUB_TOKEN: ${{ secrets.MEOWRSTRIGGER }}
        run: node index.js
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin global
          git checkout global
          git add meowrs.json
          git add repo.json
          git diff --cached --quiet && exit 0
          git commit -m "Update global repository"
          git push
