name: Request Update

on:
  workflow_dispatch:
  repository_dispatch:
    types: [request-update-run-action]

jobs:
  generate:
    name: Generate repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, global]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - name: Run generator
        env:
          GITHUB_TOKEN: ${{ secrets.MEOWRSTRIGGER }}
        run: node index.js
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin ${{ matrix.branch }}
          git checkout ${{ matrix.branch }}
          git add meowrs.json
          git add repo.json
          git diff --cached --quiet && exit 0
          git commit -m "Update ${{ matrix.branch }} repository"
          git push
